[project]
name = "atlasnova-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.4.2",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-google-genai>=4.4.0",
    "langchain-openai>=1.6.3",
    "langchain-openrouter>=0.2.8",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.2.12",
    "pypdf>=6.19.0",
    "pysqlite3-binary>=0.5.4.post2",
    "python-dotenv>=1.2.3",
]
